// let arr=["january","july","march","august"];
// arr.splice(0,2,"july","june");
// console.log(arr);
// let lang=["c","c++","html","javascript","python","java","c#","sql"];
// console.log(lang);
// lang.reverse();
// console.log(lang);
// console.log(lang.indexOf("javascript"));
let arr=["c","html","c++","python","javascript","java","sql","c#"];
let arr1=["soij","spdji"];
console.log(arr);
arr.sort();
console.log(arr);
console.log(arr.concat(arr1));
arr.reverse();
console.log(arr);
console.log(arr.slice(3));
console.log(arr.slice(-2));
console.log("---------------------");
arr1.splice(0,1,"afa","faf");
console.log(arr1);
